http:
  port: 9999
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/getServiceRequest/*'
serviceEndpoints:
  getServiceRequest:
    url: 'http://rhsoatstapp1.ci.raleigh.nc.us:8182/RaleighAPI/cityworks/'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - name: default
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: getServiceRequest 
              changeOrigin: true
